# 定义 JavaScript Array 和 String 方法及示例参数
methods = {
    "Array": {
        "constructor": [],
        "at": ["tmp_num"],
        "concat": ["tmp_array"],
        "copyWithin": ["tmp_num", "tmp_num"],
        "fill": ["tmp_str"],
        "find": ["element => element === 'example'"],
        "findIndex": ["element => element === 'example'"],
        "findLast": ["element => element === 'example'"],
        "findLastIndex": ["element => element === 'example'"],
        "lastIndexOf": ["tmp_str"],
        "pop": [],
        "push": ["tmp_str"],
        "reverse": [],
        "shift": [],
        "unshift": ["tmp_str"],
        "slice": ["tmp_num", "tmp_num"],
        "sort": [],
        "splice": ["tmp_num", "tmp_num"],
        "includes": ["tmp_str"],
        "indexOf": ["tmp_str"],
        "join": ["tmp_str"],
        "keys": [],
        "entries": [],
        "values": [],
        "forEach": ["element => console.log(element)"],
        "filter": ["element => element.length > 4"],
        "flat": [],
        "flatMap": ["element => [element]"],
        "map": ["element => element.toUpperCase()"],
        "every": ["element => element.length > 4"],
        "some": ["element => element.length > 4"],
        "reduce": ["(accumulator, currentValue) => accumulator + currentValue"],
        "reduceRight": ["(accumulator, currentValue) => accumulator + currentValue"],
        "toReversed": [],
        "toSorted": [],
        "toSpliced": ["tmp_num", "tmp_num"],
        "with": ["tmp_num", "tmp_str"],
        "toLocaleString": [],
        "toString": []
    },
    "String": {
        "constructor": [],
        "anchor": ["'name'"],
        "at": ["tmp_num"],
        "big": [],
        "blink": [],
        "bold": [],
        "charAt": ["tmp_num"],
        "charCodeAt": ["tmp_num"],
        "codePointAt": ["tmp_num"],
        "concat": ["tmp_str"],
        "endsWith": ["'test'"],
        "fontcolor": ["'color'"],
        "fontsize": ["'size'"],
        "fixed": [],
        "includes": ["'test'"],
        "indexOf": ["'test'"],
        "isWellFormed": [],
        "italics": [],
        "lastIndexOf": ["'test'"],
        "link": ["'url'"],
        "localeCompare": ["'test'"],
        "match": ["/test/"],
        "matchAll": ["/test/g"],
        "normalize": ["'NFC'"],
        "padEnd": ["tmp_num", "'0'"],
        "padStart": ["tmp_num", "'0'"],
        "repeat": ["tmp_num"],
        "replace": ["/test/", "'replace'"],
        "replaceAll": ["/test/g", "'replace'"],
        "search": ["/test/"],
        "slice": ["tmp_num", "tmp_num"],
        "small": [],
        "split": ["' '", "tmp_num"],
        "strike": [],
        "sub": [],
        "substr": ["tmp_num", "tmp_num"],
        "substring": ["tmp_num", "tmp_num"],
        "sup": [],
        "startsWith": ["'test'"],
        "toString": [],
        "toWellFormed": [],
        "trim": [],
        "trimStart": [],
        "trimLeft": [],
        "trimEnd": [],
        "trimRight": [],
        "toLocaleLowerCase": [],
        "toLocaleUpperCase": [],
        "toLowerCase": [],
        "toUpperCase": [],
        "valueOf": []
    },
}
