# 定义 JavaScript Array 和 String 方法及示例参数
array_methods = {
    "constructor": [],
    "at": ["0"],
    "concat": ["['example']"],
    "copyWithin": ["0", "1"],
    "fill": ["'example'"],
    "find": ["element => element === 'example'"],
    "findIndex": ["element => element === 'example'"],
    "findLast": ["element => element === 'example'"],
    "findLastIndex": ["element => element === 'example'"],
    "lastIndexOf": ["'example'"],
    "pop": [],
    "push": ["'example'"],
    "reverse": [],
    "shift": [],
    "unshift": ["'example'"],
    "slice": ["1", "2"],
    "sort": [],
    "splice": ["0", "1"],
    "includes": ["'example'"],
    "indexOf": ["'example'"],
    "join": ["', '"],
    "keys": [],
    "entries": [],
    "values": [],
    "forEach": ["element => console.log(element)"],
    "filter": ["element => element.length > 4"],
    "flat": [],
    "flatMap": ["element => [element]"],
    "map": ["element => element.toUpperCase()"],
    "every": ["element => element.length > 4"],
    "some": ["element => element.length > 4"],
    "reduce": ["(accumulator, currentValue) => accumulator + currentValue"],
    "reduceRight": ["(accumulator, currentValue) => accumulator + currentValue"],
    "toReversed": [],
    "toSorted": [],
    "toSpliced": ["0", "1"],
    "with": ["0", "'newValue'"],
    "toLocaleString": [],
    "toString": []
}

string_methods = {
    "constructor": [],
    "anchor": ["'name'"],
    "at": ["0"],
    "big": [],
    "blink": [],
    "bold": [],
    "charAt": ["0"],
    "charCodeAt": ["0"],
    "codePointAt": ["0"],
    "concat": ["'example'"],
    "endsWith": ["'test'"],
    "fontcolor": ["'color'"],
    "fontsize": ["'size'"],
    "fixed": [],
    "includes": ["'test'"],
    "indexOf": ["'test'"],
    "isWellFormed": [],
    "italics": [],
    "lastIndexOf": ["'test'"],
    "link": ["'url'"],
    "localeCompare": ["'test'"],
    "match": ["/test/"],
    "matchAll": ["/test/g"],
    "normalize": ["'NFC'"],
    "padEnd": ["10", "'0'"],
    "padStart": ["10", "'0'"],
    "repeat": ["3"],
    "replace": ["/test/", "'replace'"],
    "replaceAll": ["/test/g", "'replace'"],
    "search": ["/test/"],
    "slice": ["1", "3"],
    "small": [],
    "split": ["' '", "3"],
    "strike": [],
    "sub": [],
    "substr": ["1", "3"],
    "substring": ["1", "3"],
    "sup": [],
    "startsWith": ["'test'"],
    "toString": [],
    "toWellFormed": [],
    "trim": [],
    "trimStart": [],
    "trimLeft": [],
    "trimEnd": [],
    "trimRight": [],
    "toLocaleLowerCase": [],
    "toLocaleUpperCase": [],
    "toLowerCase": [],
    "toUpperCase": [],
    "valueOf": []
}